# fly.toml app configuration file generated for ppy-hm on 2025-09-18T15:01:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ppy-hm'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.24.6'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
